version: '3'

services:
  django:
    build: .
    volumes:
      - .:/kudrinka_django
      - ./static/:/kudrinka/static
    ports:
      - '8000:8000'
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'kudrinka'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./kudrinka:/var/lib/mysql_kudr

