# Generated by Django 2.1.2 on 2022-10-29 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Текст')),
                ('text', models.TextField(max_length=250, verbose_name='Текст')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('date_until', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата, до которой объявление актуально')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Choreographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField(max_length=50, verbose_name='Фамилия')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('first_name', models.TextField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.TextField(blank=True, max_length=50, verbose_name='Отчество')),
                ('phone', models.TextField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/choreographers')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Хореограф',
                'verbose_name_plural': 'Хореографы',
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField(max_length=50, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(max_length=50, null=True, verbose_name='Время окончания')),
                ('address', models.TextField(blank=True, max_length=350, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Расписание класса',
                'verbose_name_plural': 'Расписание классов',
                'ordering': ['begin_time'],
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Концерт', max_length=50, verbose_name='Название концерта')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('begin_date', models.DateField(null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('begin_time', models.TimeField(blank=True, max_length=50, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, max_length=50, null=True, verbose_name='Время окончания')),
                ('place', models.TextField(blank=True, max_length=50, verbose_name='Место проведения')),
                ('address', models.TextField(blank=True, max_length=50, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Концерт',
                'verbose_name_plural': 'Концерты',
                'ordering': ['begin_date'],
            },
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('name', models.TextField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Элемент костюма',
                'verbose_name_plural': 'Элементы костюма',
                'ordering': ['dance'],
            },
        ),
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=80, verbose_name='Название танца')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('duration', models.TimeField(blank=True, verbose_name='Длительность')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Танец',
                'verbose_name_plural': 'Танцы',
            },
        ),
        migrations.CreateModel(
            name='DanceInConcert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер танца в концерте')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Concert')),
                ('dance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Dance')),
            ],
            options={
                'verbose_name': 'Танец в концерте',
                'verbose_name_plural': 'Танцы в концерте',
                'ordering': ['concert'],
            },
        ),
        migrations.CreateModel(
            name='DanceStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance_style', models.TextField(max_length=50, verbose_name='Танцевальное направление')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Танцевальное направление',
                'verbose_name_plural': 'Танцевальные направления',
            },
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название')),
                ('num', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cost', models.PositiveIntegerField(blank=True, verbose_name='Стоимость единицы')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('bought', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Затраты',
                'verbose_name_plural': 'Затраты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.PositiveIntegerField(verbose_name='Оплачено')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('all_fonds_null', models.BooleanField(default=False)),
                ('last_year_debt', models.PositiveIntegerField(default=0, verbose_name='Недосдал в прошлом году')),
            ],
            options={
                'verbose_name': 'Фонд',
                'verbose_name_plural': 'Фонд',
                'ordering': ['sum', 'participant'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название группы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('ages', models.TextField(blank=True, max_length=50, verbose_name='Возрастная категория')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
                ('payment', models.PositiveIntegerField(blank=True, default=2000, verbose_name='Сумма оплаты')),
                ('num', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='GroupChoreographerSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField(max_length=50, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(max_length=50, null=True, verbose_name='Время окончания')),
                ('address', models.TextField(blank=True, max_length=350, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('choreographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Choreographer')),
                ('dance_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.DanceStyle')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['group', 'day_of_the_week'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.TextField(blank=True, max_length=15, verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяцы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='URL')),
                ('text', models.TextField(blank=True, max_length=10000, verbose_name='Текст')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/news')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OtherSourceOfFinances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название')),
                ('sum', models.PositiveIntegerField(default=1, verbose_name='Сумма')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Другой источник финансирования',
                'verbose_name_plural': 'Другие источники финансирования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField(max_length=50, verbose_name='Фамилия')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('first_name', models.TextField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.TextField(blank=True, max_length=50, verbose_name='Отчество')),
                ('phone', models.TextField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/participants')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
                ('moderator', models.BooleanField(default=False, verbose_name='Модератор')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kudr_app.Group')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['group', 'last_name', 'first_name', 'patronymic'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantConcert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Concert')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant')),
            ],
            options={
                'verbose_name': 'Участник-концерт',
                'verbose_name_plural': 'Участник-концерт',
                'ordering': ['concert'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantCostume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_return_before', models.DateTimeField(blank=True, null=True, verbose_name='Вернуть до')),
                ('returned', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('costume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Costume')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant')),
            ],
            options={
                'verbose_name': 'Участник-костюм',
                'verbose_name_plural': 'Участник-костюм',
                'ordering': ['costume'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantDanceConcert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('under_question', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('dance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.DanceInConcert')),
                ('participant_concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.ParticipantConcert')),
            ],
            options={
                'verbose_name': 'Участник-танец-концерт',
                'verbose_name_plural': 'Участник-танец-концерт',
                'ordering': ['participant_concert'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Month')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('main_picture', models.ImageField(default='media/default/photo/НОМЕР4.jpg', upload_to='media/photo_gallery')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фотогалерея',
                'verbose_name_plural': 'Фотогалереи',
            },
        ),
        migrations.CreateModel(
            name='PhotoInGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/photo_gallery')),
                ('date', models.DateTimeField(blank=True, verbose_name='Дата')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.PhotoGallery')),
            ],
            options={
                'verbose_name': 'Фотография в фотогалерее',
                'verbose_name_plural': 'Фотографии в фотогалерее',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.TextField(blank=True, max_length=50, verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.AddField(
            model_name='groupchoreographerschedule',
            name='day_of_the_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.WeekDay'),
        ),
        migrations.AddField(
            model_name='groupchoreographerschedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Group'),
        ),
        migrations.AddField(
            model_name='fond',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant'),
        ),
        migrations.AddField(
            model_name='costume',
            name='dance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Dance'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Group'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant'),
        ),
    ]
