# Generated by Django 2.1.4 on 2019-02-23 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choreographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('first_name', models.TextField(blank=True, max_length=50, verbose_name='Имя')),
                ('patronymic', models.TextField(blank=True, max_length=50, verbose_name='Отчество')),
                ('phone', models.TextField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/choreographers')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Хореограф',
                'verbose_name': 'Хореограф',
            },
        ),
        migrations.CreateModel(
            name='ChoreographerDanceStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choreographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Choreographer')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.TextField(blank=True, max_length=50, verbose_name='День недели')),
                ('time', models.TimeField(blank=True, max_length=50, null=True, verbose_name='Время')),
                ('address', models.TextField(blank=True, max_length=50, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
                ('choreographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.ChoreographerDanceStyle')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, verbose_name='Название концерта')),
                ('date', models.DateField(blank=True, verbose_name='Дата')),
                ('time', models.TimeField(blank=True, verbose_name='Время')),
                ('place', models.TextField(blank=True, max_length=50, verbose_name='Место проведения')),
                ('address', models.TextField(blank=True, max_length=50, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, verbose_name='Название танца')),
                ('duration', models.TimeField(blank=True, verbose_name='Длительность')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/dance')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='DanceInConcert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(null=True, verbose_name='Порядковый номер танца в концерте')),
                ('num_persons', models.PositiveIntegerField(blank=True, verbose_name='Количество человек')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Concert')),
                ('dance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Dance')),
            ],
        ),
        migrations.CreateModel(
            name='DanceStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance_style', models.TextField(blank=True, max_length=50, verbose_name='Танцевальное направление')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Танцевальное направление',
                'verbose_name': 'Танцевальное направление',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, verbose_name='Название группы')),
                ('ages', models.TextField(blank=True, max_length=50, verbose_name='Возрастная категория')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, max_length=50, verbose_name='Текст')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/news')),
                ('date', models.DateTimeField(blank=True, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('first_name', models.TextField(blank=True, max_length=50, verbose_name='Имя')),
                ('patronymic', models.TextField(blank=True, max_length=50, verbose_name='Отчество')),
                ('phone', models.TextField(blank=True, max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/participants')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, max_length=50, verbose_name='Пол')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kudr_app.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantConcert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Concert')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantDanceConcert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.DanceInConcert')),
                ('participant_concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.ParticipantConcert')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallerySubFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, verbose_name='Название')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/photo_gallery')),
                ('date', models.DateTimeField(blank=True, verbose_name='Дата')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.PhotoGallery')),
            ],
        ),
        migrations.AddField(
            model_name='classschedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Group'),
        ),
        migrations.AddField(
            model_name='choreographerdancestyle',
            name='dance_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.DanceStyle'),
        ),
    ]
