# Generated by Django 2.1.4 on 2019-02-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choreographer',
            options={'verbose_name': 'Хореограф', 'verbose_name_plural': 'Хореографы'},
        ),
        migrations.AlterModelOptions(
            name='classschedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'Концерт', 'verbose_name_plural': 'Концерты'},
        ),
        migrations.AlterModelOptions(
            name='dance',
            options={'verbose_name': 'Танец', 'verbose_name_plural': 'Танцы'},
        ),
        migrations.AlterModelOptions(
            name='danceinconcert',
            options={'verbose_name': 'Танец в концерте', 'verbose_name_plural': 'Танцы в концерте'},
        ),
        migrations.AlterModelOptions(
            name='dancestyle',
            options={'verbose_name': 'Танцевальное направление', 'verbose_name_plural': 'Танцевальные направления'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='photogallery',
            options={'verbose_name': 'Фотогалерея', 'verbose_name_plural': 'Фотогалереи'},
        ),
        migrations.AlterModelOptions(
            name='photogallerysubfolder',
            options={'verbose_name': 'Папка в фотогалерее', 'verbose_name_plural': 'Папки в фотогалерее'},
        ),
    ]
