# Generated by Django 2.1.4 on 2019-02-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0002_auto_20190223_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='description',
            field=models.TextField(blank=True, max_length=50, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='danceinconcert',
            name='description',
            field=models.TextField(blank=True, max_length=50, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='description',
            field=models.TextField(blank=True, max_length=50, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='photogallerysubfolder',
            name='description',
            field=models.TextField(blank=True, max_length=50, verbose_name='Описание'),
        ),
    ]
