# Generated by Django 2.1.4 on 2019-02-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0003_auto_20190224_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danceinconcert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='danceinconcert',
            name='num_persons',
        ),
        migrations.RemoveField(
            model_name='danceinconcert',
            name='number',
        ),
    ]
