# Generated by Django 2.1.4 on 2019-02-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0004_auto_20190224_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoGallerySubFolder',
            new_name='PhotoInGallery',
        ),
        migrations.AlterModelOptions(
            name='danceinconcert',
            options={},
        ),
        migrations.AlterModelOptions(
            name='photoingallery',
            options={'verbose_name': 'Фотография в фотогалерее', 'verbose_name_plural': 'Фотографии в фотогалерее'},
        ),
    ]
