# Generated by Django 2.1.4 on 2019-02-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0005_auto_20190224_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Choreographer_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choreographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.ChoreographerDanceStyle')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='choreographer',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='group',
        ),
    ]
