# Generated by Django 2.1.4 on 2019-02-23 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0006_auto_20190224_0053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_Choreographer_Schedule',
            new_name='GroupChoreographerSchedule',
        ),
    ]
