# Generated by Django 2.1.4 on 2019-02-23 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0007_auto_20190224_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchoreographerschedule',
            name='class_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kudr_app.ClassSchedule'),
            preserve_default=False,
        ),
    ]
