# Generated by Django 2.1.4 on 2019-02-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0008_groupchoreographerschedule_class_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchoreographerschedule',
            name='dance_style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kudr_app.DanceStyle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupchoreographerschedule',
            name='choreographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Choreographer'),
        ),
    ]
