# Generated by Django 2.1.4 on 2019-02-23 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0009_auto_20190224_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.TextField(blank=True, max_length=50, verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.AlterModelOptions(
            name='classschedule',
            options={'verbose_name': 'Расписание класса', 'verbose_name_plural': 'Расписание классов'},
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='day_of_the_week',
        ),
        migrations.AddField(
            model_name='groupchoreographerschedule',
            name='day_of_the_week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kudr_app.WeekDay'),
            preserve_default=False,
        ),
    ]
