# Generated by Django 2.1.4 on 2019-02-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0010_auto_20190224_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='time',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='begin_time',
            field=models.TimeField(blank=True, max_length=50, null=True, verbose_name='Время начала'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='end_time',
            field=models.TimeField(blank=True, max_length=50, null=True, verbose_name='Время окончания'),
        ),
    ]
