# Generated by Django 2.1.4 on 2019-02-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0011_auto_20190226_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='time',
        ),
        migrations.AddField(
            model_name='concert',
            name='begin_time',
            field=models.TimeField(blank=True, max_length=50, null=True, verbose_name='Время начала'),
        ),
        migrations.AddField(
            model_name='concert',
            name='end_time',
            field=models.TimeField(blank=True, max_length=50, null=True, verbose_name='Время окончания'),
        ),
    ]
