# Generated by Django 2.1.4 on 2019-02-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0012_auto_20190226_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='gender',
        ),
    ]
