# Generated by Django 2.1.4 on 2019-03-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0014_location_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
