# Generated by Django 2.1.4 on 2019-03-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0015_remove_location_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
