# Generated by Django 2.1.4 on 2019-03-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0016_auto_20190311_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
