# Generated by Django 2.1.4 on 2019-03-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0017_auto_20190311_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancestyle',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/dance_style'),
        ),
    ]
