# Generated by Django 2.1.4 on 2019-03-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0018_dancestyle_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreographer',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
    ]
