# Generated by Django 2.1.4 on 2019-03-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0019_choreographer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choreographer',
            name='slug',
        ),
    ]
