# Generated by Django 2.1.4 on 2019-03-18 15:38

from django.db import migrations, models
from Kudrinka.utils import unique_slug_generator


def update_slug(apps, schema_editor):
    obj = apps.get_model("kudr_app", "News")

    for instance in obj.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.id, instance.slug)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0034_auto_20190318_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
        migrations.RunPython(update_slug, reverse_code=migrations.RunPython.noop),

    ]
