# Generated by Django 2.1.4 on 2019-04-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0040_auto_20190318_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchoreographerschedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
    ]
