# Generated by Django 2.1.4 on 2019-04-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0043_auto_20190401_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.PositiveIntegerField(blank=True, max_length=50, verbose_name='Сумма для оплаты')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant')),
            ],
            options={
                'verbose_name': 'Фонд',
            },
        ),
    ]
