# Generated by Django 2.1.4 on 2019-04-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0044_fond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fond',
            name='summ',
            field=models.PositiveIntegerField(blank=True, verbose_name='Оплачено'),
        ),
    ]
