# Generated by Django 2.1.4 on 2019-04-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0045_auto_20190402_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fond',
            old_name='summ',
            new_name='sum',
        ),
    ]
