# Generated by Django 2.1.4 on 2019-04-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0046_auto_20190402_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fond',
            options={'verbose_name': 'Фонд', 'verbose_name_plural': 'Фонд'},
        ),
    ]
