# Generated by Django 2.1.4 on 2019-04-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0047_auto_20190402_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fond',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant'),
        ),
    ]
