# Generated by Django 2.1.4 on 2019-04-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0048_auto_20190402_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.TextField(blank=True, max_length=15, verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяцы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Month')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='payment',
            field=models.PositiveIntegerField(blank=True, default=2000, max_length=5, verbose_name='Сумма оплаты'),
        ),
    ]
