# Generated by Django 2.1.4 on 2019-04-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0049_auto_20190402_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='payment',
            field=models.PositiveIntegerField(blank=True, default=2000, verbose_name='Сумма оплаты'),
        ),
    ]
