# Generated by Django 2.1.4 on 2019-04-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0050_auto_20190402_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='danceinconcert',
            name='num',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Порядковый номер танца в концерте'),
        ),
    ]
