# Generated by Django 2.1.4 on 2019-04-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0051_danceinconcert_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='date',
        ),
        migrations.AddField(
            model_name='concert',
            name='begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='concert',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
