# Generated by Django 2.1.4 on 2019-04-04 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0053_auto_20190403_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantdanceconcert',
            options={'verbose_name': 'Участник-танец-концерт', 'verbose_name_plural': 'Участник-танец-концерт'},
        ),
    ]
