# Generated by Django 2.1.4 on 2019-04-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0054_auto_20190404_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantdanceconcert',
            name='num',
            field=models.TextField(blank=True, max_length=50, verbose_name='Описание'),
        ),
    ]
