# Generated by Django 2.1.4 on 2019-04-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0055_participantdanceconcert_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantconcert',
            options={'verbose_name': 'Участник-концерт', 'verbose_name_plural': 'Участник-концерт'},
        ),
    ]
