# Generated by Django 2.1.4 on 2019-04-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0057_remove_participantdanceconcert_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceinconcert',
            name='num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер танца в концерте'),
        ),
    ]
