# Generated by Django 2.1.4 on 2019-04-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0058_auto_20190404_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('name', models.TextField(blank=True, max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание')),
                ('dance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Dance')),
            ],
            options={
                'verbose_name_plural': 'Элементы костюма',
                'verbose_name': 'Элемент костюма',
            },
        ),
        migrations.CreateModel(
            name='ParticipantCostume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_return_before', models.DateTimeField(blank=True, verbose_name='Вернуть до')),
                ('returned', models.BooleanField(default=False)),
                ('costume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Costume')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant')),
            ],
            options={
                'verbose_name_plural': 'Участник-костюм',
                'verbose_name': 'Участник-костюм',
            },
        ),
    ]
