# Generated by Django 2.1.4 on 2019-04-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0061_auto_20190405_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantdanceconcert',
            name='under_question',
            field=models.BooleanField(default=False),
        ),
    ]
