# Generated by Django 2.1.4 on 2019-04-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0062_participantdanceconcert_under_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['begin_date'], 'verbose_name': 'Концерт', 'verbose_name_plural': 'Концерты'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='participantconcert',
            order_with_respect_to='concert',
        ),
    ]
