# Generated by Django 2.1.4 on 2019-04-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0065_auto_20190406_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant'),
        ),
    ]
