# Generated by Django 2.1.4 on 2019-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0066_auto_20190406_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchoreographerschedule',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
