# Generated by Django 2.1.4 on 2019-04-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0067_auto_20190406_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='address',
            field=models.TextField(blank=True, max_length=350, verbose_name='Адрес'),
        ),
    ]
