# Generated by Django 2.1.4 on 2019-04-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0068_auto_20190406_2110'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='participantdanceconcert',
            order_with_respect_to='participant_concert',
        ),
    ]
