# Generated by Django 2.1.4 on 2019-04-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0069_auto_20190407_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantconcert',
            options={'ordering': ['concert'], 'verbose_name': 'Участник-концерт', 'verbose_name_plural': 'Участник-концерт'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='participantconcert',
            order_with_respect_to=None,
        ),
    ]
