# Generated by Django 2.1.4 on 2019-04-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0076_auto_20190407_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantconcert',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='participantdanceconcert',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='URL'),
        ),
    ]
