# Generated by Django 2.1.4 on 2019-04-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0080_participantcostume_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantcostume',
            name='slug',
        ),
    ]
