# Generated by Django 2.1.4 on 2019-04-07 12:40

from django.db import migrations, models
from Kudrinka.utils import unique_slug_generator


def update_slug(apps, schema_editor):
    obj = apps.get_model("kudr_app", "ParticipantCostume")

    for instance in obj.objects.all():
        if not instance.slug:
            instance.slug = unique_slug_generator(instance, instance.id, instance.slug)
            instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0082_participantcostume_slug'),
    ]

    operations = [


        migrations.AlterField(
            model_name='participantcostume',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='URL'),
        ),
        migrations.RunPython(update_slug, reverse_code=migrations.RunPython.noop),


    ]
