# Generated by Django 2.1.4 on 2019-04-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0083_auto_20190407_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='participantgroup',
            name='participant',
        ),
        migrations.AlterModelOptions(
            name='classschedule',
            options={'ordering': ['begin_time'], 'verbose_name': 'Расписание класса', 'verbose_name_plural': 'Расписание классов'},
        ),
        migrations.AlterModelOptions(
            name='costume',
            options={'ordering': ['dance'], 'verbose_name': 'Элемент костюма', 'verbose_name_plural': 'Элементы костюма'},
        ),
        migrations.AlterModelOptions(
            name='fond',
            options={'ordering': ['participant'], 'verbose_name': 'Фонд', 'verbose_name_plural': 'Фонд'},
        ),
        migrations.AlterModelOptions(
            name='groupchoreographerschedule',
            options={'ordering': ['group'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['group', 'last_name', 'first_name', 'patronymic'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='participantcostume',
            options={'ordering': ['costume'], 'verbose_name': 'Участник-костюм', 'verbose_name_plural': 'Участник-костюм'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['month'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.DeleteModel(
            name='ParticipantGroup',
        ),
    ]
