# Generated by Django 2.1.4 on 2019-04-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0084_auto_20190407_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['ages'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
