# Generated by Django 2.1.4 on 2019-04-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0085_auto_20190407_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant')),
            ],
        ),
    ]
