# Generated by Django 2.1.4 on 2019-04-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0086_participantgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fond',
            options={'ordering': ['sum', 'participant'], 'verbose_name': 'Фонд', 'verbose_name_plural': 'Фонд'},
        ),
    ]
