# Generated by Django 2.1.4 on 2019-04-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0088_group_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
