# Generated by Django 2.1.4 on 2019-04-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0089_auto_20190408_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['num'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='dancestyle',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Описание'),
        ),
    ]
