# Generated by Django 2.1.4 on 2019-05-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0091_auto_20190409_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreographer',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='choreographer',
            name='first_name',
            field=models.TextField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='choreographer',
            name='last_name',
            field=models.TextField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='begin_time',
            field=models.TimeField(max_length=50, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='end_time',
            field=models.TimeField(max_length=50, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='begin_date',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='name',
            field=models.TextField(default='Концерт', max_length=50, verbose_name='Название концерта'),
        ),
        migrations.AlterField(
            model_name='costume',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dance',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Название танца'),
        ),
        migrations.AlterField(
            model_name='dancestyle',
            name='dance_style',
            field=models.TextField(max_length=50, verbose_name='Танцевальное направление'),
        ),
        migrations.AlterField(
            model_name='fond',
            name='sum',
            field=models.PositiveIntegerField(verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.TextField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.TextField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='photoingallery',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Название'),
        ),
    ]
