# Generated by Django 2.1.4 on 2019-05-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0092_auto_20190505_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreographer',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
