# Generated by Django 2.1.4 on 2019-05-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0093_auto_20190505_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/photo_gallery'),
        ),
    ]
