# Generated by Django 2.1.4 on 2019-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0094_photogallery_main_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='main_picture',
            field=models.ImageField(default='media/default/photo/НОМЕР4.jpg', upload_to='media/photo_gallery'),
        ),
    ]
