# Generated by Django 2.1.4 on 2019-05-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0095_auto_20190507_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreographer',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
