# Generated by Django 2.1.4 on 2019-05-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0097_auto_20190507_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название')),
                ('num', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cost', models.PositiveIntegerField(blank=True, verbose_name='Стоимость единицы')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('bought', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'Затраты',
                'verbose_name': 'Затраты',
                'ordering': ['name'],
            },
        ),
    ]
