# Generated by Django 2.1.4 on 2019-05-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0098_expence'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSourceOfFinances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название')),
                ('sum', models.PositiveIntegerField(default=1, verbose_name='Сумма')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Другой источник финансирования',
                'verbose_name_plural': 'Другие источники финансирования',
                'ordering': ['name'],
            },
        ),
    ]
