# Generated by Django 2.1.4 on 2019-05-11 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0099_othersourceoffinances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 11, 13, 3, 0, 256128), verbose_name='Дата'),
        ),
    ]
