# Generated by Django 2.1.4 on 2019-05-11 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0101_auto_20190511_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Текст')),
                ('text', models.TextField(max_length=250, verbose_name='Текст')),
                ('date', models.DateField(default=datetime.datetime(2019, 5, 11, 17, 42, 0, 697724), verbose_name='Дата')),
                ('date_until', models.DateField(blank=True, default=datetime.datetime(2019, 5, 11, 17, 42, 0, 697724), null=True, verbose_name='Дата, до которой объявление актуально')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Group')),
                ('participant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 17, 42, 0, 688748), verbose_name='Дата'),
        ),
    ]
