# Generated by Django 2.1.4 on 2019-05-11 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0103_auto_20190511_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 18, 59, 34, 354402), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 11, 18, 59, 34, 354402), null=True, verbose_name='Дата, до которой объявление актуально'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Group'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kudr_app.Participant'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 18, 59, 34, 340437), verbose_name='Дата'),
        ),
    ]
