# Generated by Django 2.1.4 on 2019-05-12 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0105_auto_20190511_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchoreographerschedule',
            options={'ordering': ['group', 'day_of_the_week'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.RemoveField(
            model_name='groupchoreographerschedule',
            name='class_schedule',
        ),
        migrations.AddField(
            model_name='groupchoreographerschedule',
            name='address',
            field=models.TextField(blank=True, max_length=350, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='groupchoreographerschedule',
            name='begin_time',
            field=models.TimeField(max_length=50, null=True, verbose_name='Время начала'),
        ),
        migrations.AddField(
            model_name='groupchoreographerschedule',
            name='description',
            field=models.TextField(blank=True, max_length=50, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='groupchoreographerschedule',
            name='end_time',
            field=models.TimeField(max_length=50, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 10, 9, 53, 180159, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 12, 10, 9, 53, 180159, tzinfo=utc), null=True, verbose_name='Дата, до которой объявление актуально'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 10, 9, 53, 170185, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
