# Generated by Django 2.1.4 on 2019-05-12 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0106_auto_20190512_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choreographerdancestyle',
            name='choreographer',
        ),
        migrations.RemoveField(
            model_name='choreographerdancestyle',
            name='dance_style',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 10, 37, 41, 459644, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 12, 10, 37, 41, 459644, tzinfo=utc), null=True, verbose_name='Дата, до которой объявление актуально'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 10, 37, 41, 450670, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.DeleteModel(
            name='ChoreographerDanceStyle',
        ),
    ]
