# Generated by Django 2.1.4 on 2019-05-14 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0107_auto_20190512_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 10, 51, 36, 267584, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 14, 10, 51, 36, 267584, tzinfo=utc), null=True, verbose_name='Дата, до которой объявление актуально'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 10, 51, 36, 254885, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='participantcostume',
            name='date_return_before',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Вернуть до'),
        ),
    ]
