# Generated by Django 2.1.4 on 2019-05-14 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0110_auto_20190514_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 12, 49, 39, 630865, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 14, 12, 49, 39, 630865, tzinfo=utc), null=True, verbose_name='Дата, до которой объявление актуально'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 12, 49, 39, 614915, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
