# Generated by Django 2.1.4 on 2019-05-14 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0111_auto_20190514_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 12, 51, 40, 553171, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_until',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 14, 12, 51, 40, 553171, tzinfo=utc), null=True, verbose_name='Дата, до которой объявление актуально'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
