# Generated by Django 2.1.4 on 2019-06-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0113_auto_20190514_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dance',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='dancestyle',
            name='picture',
        ),
    ]
