# Generated by Django 2.1.4 on 2019-08-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0114_auto_20190608_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=70, unique=True, verbose_name='URL'),
        ),
    ]
