# Generated by Django 2.1.4 on 2019-08-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0115_auto_20190819_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
