# Generated by Django 2.1.4 on 2019-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0116_participant_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='moderator',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
    ]
