# Generated by Django 2.1.4 on 2019-09-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0117_auto_20190829_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='fond',
            name='all_fonds_null',
            field=models.BooleanField(default=False),
        ),
    ]
