# Generated by Django 2.1.4 on 2019-09-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudr_app', '0118_fond_all_fonds_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='fond',
            name='last_year_debt',
            field=models.PositiveIntegerField(default=0, verbose_name='Недосдал в прошлом году'),
        ),
    ]
